ClickHouse db support
vkorobkov/jfixtures pull request #12
Opened 2017-07-17 12:01 UTC by rodionovsasha

2017-07-17 17:48 UTC, vkorobkov commented on pom.xml
> +    <version>1.0.7</version>
:+1:

2017-07-17 17:52 UTC, vkorobkov requested changes
Let's update `README.md`: there is a phrase "Postgres and MySql are supported at the moment".
Let's change it to:
```
Databases which JFixtures supports:
* Postgres
* MySql
* H2
* Yandex ClickHouse
```

2017-07-18 06:12 UTC, rodionovsasha commented
@vkorobkov README.md has been updated

2017-07-18 19:45 UTC, vkorobkov approved these changes

2017-07-18 19:45 UTC, merged