Feature/h2 db support
vkorobkov/jfixtures pull request #6
Opened 2017-07-12 12:48 UTC by rodionovsasha

2017-07-12 18:30 UTC, vkorobkov requested changes
Looks good though some polishing around is required

2017-07-12 18:30 UTC, vkorobkov commented on README.md
> +* It is hard to match values to columns:
:+1:

2017-07-12 18:30 UTC, vkorobkov commented on README.md
> +* SQL script as a result
:+1:

2017-07-12 18:30 UTC, vkorobkov commented on src/test/groovy/com/github/vkorobkov/jfixtures/integration/H2IntegrationTest.groovy
> +        sql.execute("CREATE TABLE IF NOT EXISTS users (ID INT PRIMARY KEY, NAME varchar(50) DEFAULT NULL, AGE INT DEFAULT NULL)")
Should we try to drop the table(if exists) before we create a new one?

2017-07-12 18:30 UTC, vkorobkov commented on src/test/groovy/com/github/vkorobkov/jfixtures/sql/DataSourceUtil.groovy
> +    private static final String DATASOURCE_URL = "jdbc:h2:mem:jfixturesDb;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false"
`String` type could be removed - groovy understands

2017-07-12 18:30 UTC, vkorobkov commented on src/test/groovy/com/github/vkorobkov/jfixtures/sql/DataSourceUtil.groovy
> +    @Shared
So we need `@Shared` given the field is already static?

2017-07-12 18:30 UTC, vkorobkov commented on src/test/groovy/com/github/vkorobkov/jfixtures/sql/DataSourceUtil.groovy
> +    public static groovy.sql.Sql sql = new groovy.sql.Sql(getDataSource())
Take a look at `groovy.lang.Lazy` - probably we can just do something like:
```
@Lazy
static Sql sql = {
    def dataSource = new BasicDataSource()
    dataSource.url = DATASOURCE_URL
    new Sql(dataSource)
}()
```

or even:
```
@Lazy
static def sql = new Sql(new BasicDataSource(url: DATASOURCE_URL))
```

2017-07-12 18:30 UTC, vkorobkov commented on src/test/resources/integration/h2_integration_test/default.yml
> +"users.yml":
Let's add a few more rows?

2017-07-12 18:30 UTC, vkorobkov commented on src/test/groovy/com/github/vkorobkov/jfixtures/integration/H2IntegrationTest.groovy
> +        sql.execute(JFixtures.h2(tmpFolderPath as String).asString())
I'd create a new groovy `trait` like that and extend H2 tests from it:
```
trait H2Test extends YamlVirtualFolder {
   Sql getSql() { DataSourceUtil.sql }
   def executeFixtures(def folderPath) {
      sql.execute(JFixtures.h2(folderPath as String).asString())
   } 
}
```

2017-07-13 05:21 UTC, rodionovsasha commented on src/test/groovy/com/github/vkorobkov/jfixtures/integration/H2IntegrationTest.groovy
> +        sql.execute("CREATE TABLE IF NOT EXISTS users (ID INT PRIMARY KEY, NAME varchar(50) DEFAULT NULL, AGE INT DEFAULT NULL)")
done

2017-07-13 05:43 UTC, rodionovsasha commented on src/test/groovy/com/github/vkorobkov/jfixtures/integration/H2IntegrationTest.groovy
> +        sql.execute(JFixtures.h2(tmpFolderPath as String).asString())
done

2017-07-13 05:45 UTC, rodionovsasha commented on src/test/groovy/com/github/vkorobkov/jfixtures/sql/DataSourceUtil.groovy
> +    private static final String DATASOURCE_URL = "jdbc:h2:mem:jfixturesDb;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false"
done

2017-07-13 05:53 UTC, rodionovsasha commented on src/test/groovy/com/github/vkorobkov/jfixtures/sql/DataSourceUtil.groovy
> +    @Shared
Hm, not really and can be removed.. But @Shared is more for readers to show them that this variable is the same for all feature methods.. making tests more readable.

2017-07-13 05:58 UTC, rodionovsasha commented on src/test/groovy/com/github/vkorobkov/jfixtures/sql/DataSourceUtil.groovy
> +    public static groovy.sql.Sql sql = new groovy.sql.Sql(getDataSource())
wonderful code!

2017-07-13 07:15 UTC, vkorobkov commented on src/test/groovy/com/github/vkorobkov/jfixtures/sql/DataSourceUtil.groovy
> +    static def sql = new groovy.sql.Sql(new BasicDataSource(url: DATASOURCE_URL))
:+1:

2017-07-13 07:16 UTC, vkorobkov commented on src/test/groovy/com/github/vkorobkov/jfixtures/util/WithResourceTest.groovy
> +    def "broadcasts the exception when the resource is null and function fails"() {
:+1:

2017-07-13 07:16 UTC, vkorobkov commented on src/test/groovy/com/github/vkorobkov/jfixtures/loader/ValueTypeTest.groovy
> -    def "valueOfIgnoreCase throws exceptin when wrong value is provided"() {
:+1:

2017-07-13 07:17 UTC, vkorobkov commented on src/test/groovy/com/github/vkorobkov/jfixtures/loader/ValueTypeTest.groovy
> +    def "valueOfIgnoreCase throws exception when wrong value is provided"() {
:+1:

2017-07-13 07:28 UTC, vkorobkov commented on src/test/groovy/com/github/vkorobkov/jfixtures/integration/H2IntegrationTest.groovy
> +        sql.execute("DROP TABLE IF EXISTS users")
Does it create a table before every test method of before all the methods?

2017-07-13 07:29 UTC, rodionovsasha commented on src/test/groovy/com/github/vkorobkov/jfixtures/integration/H2IntegrationTest.groovy
> +        sql.execute("DROP TABLE IF EXISTS users")
run before the first feature method

2017-07-13 07:30 UTC, vkorobkov commented on src/test/groovy/com/github/vkorobkov/jfixtures/integration/H2IntegrationTest.groovy
> +        sql.execute("DROP TABLE IF EXISTS users")
Maybe we'll need some pretty API in `H2Test` trait for dropping and creating a new table.

Would be nice just to call a methods like: `recreateTable("users", [ID: "INT PRIMARY KEY", NAME: "varchar(50) DEFAULT NULL", AGE: "GE INT DEFAULT NULL")`

2017-07-17 06:53 UTC, vkorobkov approved these changes

2017-07-17 06:55 UTC, merged